### ISSUE TITLE
Pysnmp doesn't install Pysmi itself

### ISSUE THREAD

**Issue by umair-zink** [lextudio/pysnmp#130] opened 2024-10-08 10:58 UTC
### Expected behavior

pip install pysnmp

should install all its dependent packages/modules.

### Actual behavior

Pysmi doesn't get installed while installing Pysnmp.

### Detailed steps

I have been running pysnmp for past 2 months, i never installed any of its dependent modules/packages separately, but today when i deployed my docker application, it started complaining about Pysmi package which i had to install separately. Here is the output of the error and the resolution i adopted.

```
root@5411ad28f80d:/usr/app/src# python pysnmp_listen.py
Traceback (most recent call last):
  File "/usr/app/src/pysnmp_listen.py", line 17, in <module>
    compiler.addMibCompiler(mibBuilder, sources=['http://mibs.snmplabs.com/asn1/@mib@'])
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pysnmp/smi/compiler.py", line 36, in addMibCompiler
    raise error.SmiError("MIB compiler not available: %s" % errorMsg)
pysnmp.smi.error.SmiError: MIB compiler not available: No module named 'pysmi'
root@5411ad28f80d:/usr/app/src# pip show pysmi
WARNING: Package(s) not found: pysmi
root@5411ad28f80d:/usr/app/src# pip install pysmi
Collecting pysmi
  Downloading pysmi-1.5.0-py3-none-any.whl.metadata (8.0 kB)
Collecting Jinja2<4.0.0,>=3.1.3 (from pysmi)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting ply<4.0,>=3.11 (from pysmi)
  Downloading ply-3.11-py2.py3-none-any.whl.metadata (844 bytes)
Requirement already satisfied: requests<3.0.0,>=2.26.0 in /usr/local/lib/python3.13/site-packages (from pysmi) (2.32.3)
Collecting MarkupSafe>=2.0 (from Jinja2<4.0.0,>=3.1.3->pysmi)
  Downloading MarkupSafe-3.0.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.26.0->pysmi) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.26.0->pysmi) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.26.0->pysmi) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/site-packages (from requests<3.0.0,>=2.26.0->pysmi) (2024.8.30)
Downloading pysmi-1.5.0-py3-none-any.whl (84 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
Downloading MarkupSafe-3.0.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23 kB)
Installing collected packages: ply, MarkupSafe, Jinja2, pysmi
Successfully installed Jinja2-3.1.4 MarkupSafe-3.0.0 ply-3.11 pysmi-1.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@5411ad28f80d:/usr/app/src# python pysnmp_listen.py
Error in env vars.
Error in DB Connection
(<class 'NameError'>, NameError("name 'ENDPOINT' is not defined"), <traceback object at 0x7fd904987c00>)
SNMP Receiver (v3.1) running on 0.0.0.0, port 16311
^CShutting down...
root@5411ad28f80d:/usr/app/src#
```

### Python package information

root@5411ad28f80d:/usr/app/src# pip list Package            Version ------------------ --------- azure-core         1.31.0 azure-cosmos       4.7.0 certifi            2024.8.30 charset-normalizer 3.3.2 idna               3.10 Jinja2             3.1.4 MarkupSafe         3.0.0 pip                24.2 ply                3.11 pyasn1             0.6.1 pysmi              1.5.0 pysnmp             7.1.5 requests           2.32.3 six                1.16.0 typing_extensions  4.12.2 urllib3            2.2.3

### Operating system information

Debian GNU/Linux 12

### Python information

Python 3.13.0

### Relevant log output

```shell
root@5411ad28f80d:/usr/app/src# python pysnmp_listen.py
Traceback (most recent call last):
  File "/usr/app/src/pysnmp_listen.py", line 17, in <module>
    compiler.addMibCompiler(mibBuilder, sources=['http://mibs.snmplabs.com/asn1/@mib@'])
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pysnmp/smi/compiler.py", line 36, in addMibCompiler
    raise error.SmiError("MIB compiler not available: %s" % errorMsg)
pysnmp.smi.error.SmiError: MIB compiler not available: No module named 'pysmi'
```

**Comment by lextudio-support** [comment] 2024-10-08 10:58
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Closed** 2024-10-08 15:08 UTC
Labels: area:documentation, question, area:pysmi, area:pysnmp, area:faq

**Comment by lextm** [comment] 2024-10-08 15:09
This is by design if you read the release notes and the updated documentation.
