### ISSUE TITLE
[Bug]: Version 2.0.1 Cannot import send_notification from hlapi

### ISSUE THREAD

**Issue by fallinbryan** [lextudio/pysnmp#81] opened 2024-07-12 16:58 UTC
### Expected behavior

have code that sends snmp notifications, does not work with latest version published to pypl,  have to use pysnmp-lextudio==6.1.2 for send notification to work

### Actual behavior

But a bug happened like this:  cannot import send_notification from hlapi

### Detailed steps

The steps are,

### Python package information

6.2.0

### Operating system information

Windoes

### Python information

3.12.1

**Comment by robg37** [comment] 2024-07-12 17:20
I'm seeing this as well:

ImportError: cannot import name 'sendNotification' from 'pysnmp.hlapi'

**Comment by lextm** [comment] 2024-07-12 18:04
We intentionally removed the problematic sync API in release 6.2. Closed as by design.

**Closed** 2024-07-12 18:03 UTC
Labels: bug, triage
