### ISSUE TITLE
isFixedLength deprecation warning

### ISSUE THREAD

**Issue by johanreinalda** [lextudio/pysnmp#138] opened 2024-10-25 18:32 UTC
### Expected behavior

No deprecation warning.

### Actual behavior

Running pysnmp 7.1.8, under python 3.12.7, I get a deprecation warning when calling
pysnmp.hlapi.v3arch.asyncio.set_cmd():

"DeprecationWarning: isFixedLength is deprecated. Please use is_fixed_length instead."

This appears to come from smi.mibs.SNMPv2-SMI.py line 1249, 

isFixedLength() is marked as deprecated in proto.rfc1902.py at line 279

Note this is not impacting functionality...

### Detailed steps

see above.

### Python package information

7.1.8

### Operating system information

Ubuntu 22, with python 3.12.7

### Python information

python 3.12.7

**Comment by lextudio-support** [comment] 2024-10-25 18:32
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment] 2024-10-25 20:07
This is by design. The API surface is going to be reshaped in next major release, so deprecation warnings are common.

**Closed by lextm** 2024-10-25 20:07 UTC
Labels: question, area:pysnmp
